version: '3.8'
services:
  # Django App
  backend_auth:
   container_name: django_auth_api
   build: .
   volumes:
    - .:/app
   ports:
    - 8000:8000
   depends_on:
    - db
    - redis
  db:
   image: postgres
   container_name: django_auth_ddbb
   restart: always
   environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: gastonfr24
      POSTGRES_PASSWORD: admin.123#
   ports:
    - 5432:5432
   volumes:
      - .dbdata:/var/lib/postgresql
  
  # Redis Cache
  redis:
    image: redis
    container_name: django_auth_redis
    ports:
      - 6379:6379
  
  # # Event Queue Kafka
  # queue_auth:
  #   build: .
  #   command: >
  #     sh -c "python consumer.py"
  #   depends_on:
  #     - db
  
  # Database (PostgreSQL)